apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: adhp/zid-frontend
  newName: adhp/frontend
  newTag: zid-main-bb8b448
- name: adhp/zkc-frontend
  newName: adhp/frontend
  newTag: zdv-main-aacda50
- name: denartcc/api
  newName: adhp/api
  newTag: dev-7773070
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
