apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/ingress.yaml
- discord/service.yaml
- chart-parser/cronjob.yaml
images:
- name: adhp/zdv-frontend
  newName: adhp/frontend
  newTag: zdv-v1.9.1711235667.62-8b6ec15
- name: adhp/zid-frontend
  newName: adhp/frontend
  newTag: zid-v1.9.1724812259.78-d424825
- name: adhp/zkc-frontend
  newName: adhp/frontend
  newTag: zkc-v1.9.1714390132.64-6f41ec0
- name: denartcc/api
  newName: adhp/api
  newTag: main-b2362c9
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: 72032a6
